theme: jekyll-theme-dinky
title: Hi, I'm Safura SULEYMAN
description: Applied data scientist with a passion for automation, productivity, and new technologies
github:
  repository_url: https://github.com/ssuleyma
  is_user_page: false
  is_project_page: true
show_downloads: false
